sqliteInt.h: fix build when NDEBUG is defined (as assert() is no code)
Problem seen otherwise due to assert() not generating any code:

error: expected expression before ',' token
xxxxxx | #define AggInfoColumnReg(A,I)  (assert((A)->iFirstReg),(A)->iFirstReg+(I))

note: in expansion of macro 'AggInfoColumnReg'
xxxxxx |         return AggInfoColumnReg(pAggInfo, pExpr->iAgg);
       |                ^~~~~~~~~~~~~~~~
warning: left-hand operand of comma expression has no effect [-Wunused-value]
xxxxxx | #define AggInfoColumnReg(A,I)  (assert((A)->iFirstReg),(A)->iFirstReg+(I))